### ISSUE TITLE
Shadow Tint ?

### ISSUE THREAD

**Issue by calypsoup** [Aerthas/Aerthas-Unity-Shaders#1]
First of all thank you very much for the shader ! I really greatfull for the effort you put into it,
My issue is that I want to give her red-ish shadow to make her skin look smooth rather than just black shadow
adjusting light color just makes whole model go red, is it possible for you to add such feature please ?
Also smoothing for the shadow as well if possible ?
![aaaaaaaaaaaaaaaaaaaaaaaawaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/28690893/76927665-a6513100-68f0-11ea-9042-d2b473500955.png)

my discord is Soupy#4109 if you need someone to test, thank you

**Comment by Aerthas** [comment]
You were absolutely right. I was tinting the shadows based on just a gray scale multiply of the SSS, when it actually is the SSS*Base directly for the primary shadow, and (SSS^2)*Base*1.5 for the secondary darker shadow.
Thank you for pointing this out!

**Comment by calypsoup** [comment]
please feel free to close the issue when you fix it ! Thank you very much for the shader and your attention !
